project:
  type: book

book:
  site-url: https://example.com
  title: "Dictionary SMART for Health for Rangers"
  author: "Diego Montecino"
  date: "12/18/2023"
  chapters:
    - index.qmd
    - site_description.qmd

format:
  html:
    theme: cosmo

babelquarto:
  languagecodes:
  - name: es
    text: "Versión en español"
  - name: en
    text: "Version in english"
  mainlanguage: 'en'
  languages: ['es']
title-es: Diccionario SMART para Salud - Guardaparques
description-es: Descripción
author-es: Autor
lang: en
